#!/usr/bin/env node

const path = require('path');
const main = require('./main');
const clean = require('./clean');


const SCAN_PATTERN = '{*.js,**/*.js}';
const IGNORE_PATTERN = '{*.*.js,**/*.*.js}';

const argDir = process.argv[2] || '.';
const outputDirectory = process.cwd();
const directoryToScan = path.join(outputDirectory, argDir);

const cleanFlag = process.argv.includes('--clean');

const parameters = {
  scanPattern: SCAN_PATTERN,
  IGNORE_PATTERN: IGNORE_PATTERN,
  directoryToScan,
  outputDirectory,
};

if(cleanFlag){
  return clean(parameters);
}

main(parameters);
